# Generated by Django 4.1.5 on 2023-01-11 16:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_course_newentery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newentery",
            name="materials",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("NoteBook", "NoteBook"),
                    ("Exam_Paper", "Exam_Paper"),
                    ("Pen", "Pen"),
                    ("Drafter", "Drafter"),
                    ("Pencil", "Pencil"),
                ],
                max_length=15,
            ),
        ),
    ]
